# Copyright 2025 The BrightEyes Authors
# Use of this source code is governed by a GPL 3.0 license that can be
# found in the copyright file.

name: Build & Package Ubuntu GCC

on:
  push:
    branches: [ feature/add-ci-support ]

jobs:
  build-ubuntu-gcc:
    name: Ubuntu GCC
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install native build tools
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            gcc cmake make zip unzip libsdl2-dev libsdl2-mixer-dev

      - name: Host build (GCC)
        working-directory: src/gen
        run: |
          export CFLAGS="-Og -g -fno-asm -fopenmp -Wall -Wextra $(sdl2-config --cflags)"
          make -f Makefile_old clean
          make -f Makefile_old CFLAGS="${CFLAGS}"
          test -f ngen_gcc

      - name: Upload host binary
        uses: actions/upload-artifact@v4
        with:
          name: bright-eyes-linux
          path: src/gen/ngen_gcc
