#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

echo "executing ./git/hooks/pre-comit"
DIR=$PWD

# have g++ installed
g++ -v 2>/dev/null >/dev/null
if [ $? -ne 0 ]; then
	echo "ERROR: g++ not installed";
	exit 1
fi
# have gcc installed
gcc -v 2>/dev/null >/dev/null
if [ $? -ne 0 ]; then
	echo "ERROR: g++ not installed";
	exit 1
fi


# NGEN part begin
cd src/gen/

#check if NGEN builds on this system
echo -n "NGEN: Host build check: "
make -f Makefile_old clean 2>/dev/null >/dev/null
make -f Makefile_old 2>lastbuild.log >/dev/null
if [ $? -ne 0 ]; then
	echo "FAIL";
	exit 1
fi
echo "\tOK"

#check if NGEN builds on DOS
echo -n "NGEN: DOS build check: "
./tools/build.sh 2>/dev/null >/dev/null
RETVAL=$?
if [ $RETVAL -gt 0 ]; then
	echo "FAIL";
	exit 1
fi
echo "\t\tOK"

cd $DIR
# GEN part end


# GEN_DOS part begin
cd src/gen_dos/

#check if GEN builds on DOS
echo -n "GEN: DOS build check: "
./tools/build.sh 2>/dev/null >/dev/null
RETVAL=$?
if [ $RETVAL -gt 0 ]; then
	echo "FAIL";
	exit 1
fi
echo "\t\tOK"

cd $DIR
# GEN part end


# SCHICK part begin
cd src/schick/

#check if SCHICK builds on DOS
echo -n "SCHICK: DOS build check: "
./tools/build.sh 2>/dev/null >/dev/null
RETVAL=$?
if [ $RETVAL -gt 0 ]; then
	echo "FAIL";
	exit 1
fi
echo "\tOK"

cd $DIR
# SCHICK part end

exec git diff-index --check --cached $against --
